import random
n = random.randint(0, 15)
print('Guess the number generated by the computer(0-15)')

cont = "y"

while cont == "y":
    ans = input('Guess the number:')
    if int(ans) == n:
        print('Your guess was correct. Brilliant!!')
        cont = input('Do you want to play again?(y/n)')

    else:
        print('Your guess was incorrect.')
        ht1 = input('Do you want a hint?(y/n)')

        if ht1 == 'y':
            if int(ans) < n:
                print('The entered number is less please try a higer number')
            
            elif int(ans) > n:
                print('The entered number is high please try a lower number')
        
            continue